### ISSUE TITLE
[Ошибка]: Этому пользователю уже был присвоен ключ доступа!

### ISSUE THREAD

**Issue by UrbanSide** [DevCraftClub/dle_api#10]
### Пользовательское соглашение

- [X] Я прочёл / прочла соглашение и согласен / согласна с ними

### Я читал / читала документацию, перед созданием тикета

- [X] Я прочёл / прочла и ознакомился / ознакомилась с документацией

### В чём проблема?

После обновления в списке ключей прошлый пропал,новый создать немогу.

### Что ожидали?

Создать новый ключ,раз пропал старый

### Версия плагина

v160.0.33

### Версия DLE

16.x (Default)

### Версия PHP

8.x (Default)

### Скриншоты

![image](https://github.com/DevCraftClub/dle_api/assets/26259129/ead00df6-70c6-4e0a-a77b-8a74393624d5)
![image](https://github.com/DevCraftClub/dle_api/assets/26259129/4fdbcf91-ac3e-4f03-9dd3-555d6fe57d0d)

**Comment by Gokujo** [comment]
Уже завтра проверю

**Comment by UrbanSide** [comment]
![image](https://github.com/DevCraftClub/dle_api/assets/26259129/f0a41a64-b017-4076-9eb8-d7d932ea8cf4)
Дополню,удалил вручную в бд старый ключ,создал новый.Не появился в спике.Апи при запросе выдает мол ключ не верный.

**Comment by Gokujo** [comment]
[160.0.34](https://github.com/DevCraftClub/dle_api/releases/tag/160.0.34)
