### ISSUE TITLE
[Ошибка]: MySQL Syntax Error

### ISSUE THREAD

**Issue by Virass** [DevCraftClub/dle_api#11]
### Пользовательское соглашение

- [x] Я прочёл / прочла соглашение и согласен / согласна с ними

### Я читал / читала документацию, перед созданием тикета

- [X] Я прочёл / прочла и ознакомился / ознакомилась с документацией

### В чём проблема?

Установил модуль rest api для dle, настроил, но при запросе к примеру по api/v1/post/ вижу ответ об ошибке sql (ошибка на скриншоте). 
```
Unhandled Exception.
<br />SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'table = ? and key_id = ?' at line 2<br /> You can find the error back in the log.
```

Если использую ключ для гостя с проставленными всеми галочками на чтение всего, имею ошибку
```
{"error":"API-ключ не действителен!"}
```

Версия пыхи 8.2, дле 16.1, плагин 160.0.34

### Что ожидали?

Получить все посты массивом

### Версия плагина

160.0.34

### Версия DLE

16.x (Default)

### Версия PHP

8.x (Default)

### Скриншоты

![image](https://github.com/DevCraftClub/dle_api/assets/24947782/60bc04ec-7df1-4871-8b66-f42dab9e0f60)

**Comment by Virass** [comment]
Что еще нужно скинуть для локализации проблеммы?

**Comment by Gokujo** [comment]
На работе нет возможности эмулировать PHP сервер, к сожалению.

Как писал в телеграме, если не успею до четверга, то уже только после 10ого сентября

**Comment by Gokujo** [comment]
в папке [logs](https://github.com/DevCraftClub/dle_api/tree/master/upload/api/includes/logs/) должен был появиться файл логов, залей его сюда

**Comment by Virass** [comment]
[2023-08-28-079393a46624dd4513d7dba2a18268f0.txt](https://github.com/DevCraftClub/dle_api/files/12462382/2023-08-28-079393a46624dd4513d7dba2a18268f0.txt)

**Comment by Gokujo** [comment]
https://github.com/DevCraftClub/dle_api/releases/tag/v160.0.35

Прошу. Будут проблемы - обращайся
