### ISSUE TITLE
Не могу создать апи ключ

### ISSUE THREAD

**Issue by UrbanSide** [DevCraftClub/dle_api#3]
![image](https://github.com/Gokujo/dle_api/assets/26259129/c53535e5-e098-48c4-96b4-2295d0e78433)

**Comment by UrbanSide** [comment]
![image](https://github.com/DevCraftClub/dle_api/assets/26259129/16bc5650-e389-4221-8dea-9d6e4f5ac386)
![image](https://github.com/DevCraftClub/dle_api/assets/26259129/a32f7b52-a1dd-41d2-93ed-8e14a711fb4d)

**Comment by Gokujo** [comment]
понял, заполни полностью настройки. **Длина ключа** не должна быть пустой!

**Comment by UrbanSide** [comment]
> понял, заполни полностью настройки. **Длина ключа** не должна быть пустой!

принято,ключ создался.Спасибо.Будем изучать подойдет ли под мои хотелки)
